main:
  - name: Home
    url: ""
    weight: 1
  - name: TheFarm
    url: "#theFarm"
    weight: 2
  - name: News
    url: "#news"
    weight: 3
  - name: About
    url: "#about"
    weight: 4
  - name: Books
    url: "#books"
    weight: 5
  - name: Testimonials
    url: "#testimonial"
    weight: 6
  - name: Blog
    url: "#blog"
    weight: 7
sitemap:
  - name: Home
    url: ""
    weight: 1
  - name: Contact Us
    url: "contact"
    weight: 2
  - name: Books
    url: "books"
    weight: 3
  - name: Blog
    url: "blog"
    weight: 4
